{"version":3,"sources":["../../app-src/util/ApplicationException.js"],"names":["ApplicationException","Error","constructor","message","name","exception","IsApplicationException","err","Object","getPrototypeOf","getExceptionMessage","console","log"],"mappings":";;;;;;UAAaA,oB,GAAN,MAAMA,oBAAN,SAAmCC,KAAnC,CAAyC;AAC9CC,oBAAYC,UAAU,EAAtB,EAA0B;AACxB,gBAAMA,OAAN;AACA,eAAKC,IAAL,GAAY,KAAKF,WAAL,CAAiBE,IAA7B;AACD;AAJ6C,O;;;;AAOhD,YAAMC,YAAYL,oBAAlB;;AAEO,eAASM,sBAAT,CAAgCC,GAAhC,EAAqC;AAC1C,eACEA,eAAeF,SAAf,IAA4BG,OAAOC,cAAP,CAAsBF,GAAtB,aAAsCF,SADpE;AAGD;;;;AAEM,eAASK,mBAAT,CAA6BH,GAA7B,EAAkC;AACvC,YAAID,uBAAuBC,GAAvB,CAAJ,EAAiC;AAC/B,iBAAOA,IAAIJ,OAAX;AACD;AACDQ,gBAAQC,GAAR,CAAYL,GAAZ;AACA,eAAO,sCAAP;AACD","file":"ApplicationException.js","sourcesContent":["export class ApplicationException extends Error {\n  constructor(message = '') {\n    super(message)\n    this.name = this.constructor.name\n  }\n}\n\nconst exception = ApplicationException\n\nexport function IsApplicationException(err) {\n  return (\n    err instanceof exception || Object.getPrototypeOf(err) instanceof exception\n  )\n}\n\nexport function getExceptionMessage(err) {\n  if (IsApplicationException(err)) {\n    return err.message\n  }\n  console.log(err)\n  return 'Não foi possível realizar a operação'\n}\n"]}